services:
  # Database
  db:
    image: pgvector/pgvector:pg16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=main-password
      - POSTGRES_DB=study_assistant
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Test database
  db-test:
    image: pgvector/pgvector:pg16
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test-password
      - POSTGRES_DB=test_study_assistant

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules # Anonymous volume so host files don't overwrite
    depends_on:
      - backend

volumes:
  postgres_data:
