FROM python:3.14-slim

WORKDIR /app

RUN useradd -m pythonuser

# Installs dependencies
COPY --chown=pythonuser:pythonuser requirements.txt requirements-dev.txt ./backend/

RUN pip install --no-cache-dir -r backend/requirements.txt -r backend/requirements-dev.txt

# Copies the rest of the files
COPY --chown=pythonuser:pythonuser . ./backend/

USER pythonuser

CMD ["fastapi", "dev", "backend/src/main.py", "--host", "0.0.0.0", "--port", "8000"]