from datetime import datetime, timezone
from typing import TYPE_CHECKING, Annotated

from pydantic import BeforeValidator, model_validator
from sqlmodel import Column, DateTime, Field, Relationship, SQLModel

from backend.src.exceptions.core import ExceptionRequestValidation_400
from backend.src.models_schema.miscellaneous.enums import (
    StudyActivityFormat,
    StudyActivityType,
    SubjectType,
)
from backend.src.models_schema.miscellaneous.utils import beva_forbid_none

if TYPE_CHECKING:
    from backend.src.models_schema.activity.exercise_item import (
        ExerciseItem,
        ExerciseItemOutput,
    )
    from backend.src.models_schema.activity.review_item import (
        ReviewItem,
        ReviewItemOutput,
    )
    from backend.src.models_schema.interaction.interaction import Interaction

# ----- BASE ---- #


class StudyActivityBase(SQLModel):
    prompt: str | None
    activity_format: StudyActivityFormat
    subject_type: SubjectType


# ----- INPUT ----- #


class StudyActivityInput(StudyActivityBase):
    prompt: str
    document_id: int | None = None


class FlashcardsActivityInput(SQLModel):
    subject_type: SubjectType
    name: Annotated[str, Field(min_length=1)]
    description: str


# ----- OUTPUT ----- #


class StudyActivityOutput(StudyActivityBase):
    id: int
    interaction_id: int
    name: str
    description: str
    activity_type: StudyActivityType
    created_at: datetime

    is_submitted: bool
    submitted_at: datetime | None


class StudyActivityOutputComplete(StudyActivityOutput):
    items: list["ReviewItemOutput"] | list["ExerciseItemOutput"]


# ----- UPDATE ----- #


class StudyActivityUpdate(SQLModel):
    name: Annotated[
        str | None, BeforeValidator(beva_forbid_none), Field(min_length=1)
    ] = None
    description: Annotated[str | None, BeforeValidator(beva_forbid_none)] = None


# ----- TABLE MODEL ----- #


class StudyActivity(StudyActivityBase, table=True):
    __tablename__ = "study_activity"  # type: ignore

    id: Annotated[int | None, Field(primary_key=True, nullable=False)] = None
    interaction_id: Annotated[
        int | None, Field(foreign_key="interaction.id", nullable=False)
    ] = None

    # Name and description will be generated by LLM first, and then editable by user (if not manually creating, like flashcards)
    name: str
    description: str

    activity_type: StudyActivityType

    is_submitted: bool = False  # Exercise only
    is_deleted: bool = False

    created_at: Annotated[
        datetime,
        Field(
            sa_column=Column(DateTime(timezone=True)),
        ),
    ]
    submitted_at: Annotated[
        datetime | None,
        Field(sa_column=Column(DateTime(timezone=True))),
    ] = None

    interaction: "Interaction" = Relationship(back_populates="study_activities")
    review_items: list["ReviewItem"] = Relationship(
        back_populates="study_activity"
    )  # Uses soft delete
    exercise_items: list["ExerciseItem"] = Relationship(
        back_populates="study_activity"
    )  # Uses soft delete

    @model_validator(mode="after")
    def validate_type_format(self):
        if (
            self.activity_type == StudyActivityType.EXERCISE
            and self.activity_format
            not in (
                StudyActivityFormat.MULTIPLE_CHOICE_QUESTIONS,
                StudyActivityFormat.OPEN_ENDED,
            )
        ):
            raise ExceptionRequestValidation_400(
                f"Exercise activity type does not support format: {self.activity_format.value}."
            )
        elif (
            self.activity_type == StudyActivityType.REVIEW
            and self.activity_format not in (StudyActivityFormat.FLASHCARDS,)
        ):
            raise ExceptionRequestValidation_400(
                f"Review activity type does not support format: {self.activity_format.value}."
            )
        return self

    @model_validator(mode="after")
    def validate_prompt_exists(self):
        if (
            self.activity_format != StudyActivityFormat.FLASHCARDS
            and self.prompt is None
        ):
            raise ExceptionRequestValidation_400(
                "Prompt cannot be null for this format type."
            )
        return self

    @property
    def items(self) -> list[ExerciseItem] | list[ReviewItem]:
        if self.activity_type == StudyActivityType.EXERCISE:
            return self.exercise_items
        return self.review_items


from backend.src.models_schema.activity.exercise_item import (
    ExerciseItemOutput,
)
from backend.src.models_schema.activity.review_item import ReviewItemOutput
