from datetime import datetime, timezone
from typing import TYPE_CHECKING, Annotated

from pydantic import BeforeValidator
from sqlalchemy import CheckConstraint
from sqlmodel import Column, DateTime, Field, Relationship, SQLModel

from backend.src.models_schema.miscellaneous.enums import (
    StudyActivityFormat,
    StudyActivityType,
    SubjectType,
)
from backend.src.models_schema.miscellaneous.utils import beva_forbid_none

if TYPE_CHECKING:
    from backend.src.models_schema.activity.exercise_item import (
        ExerciseItem,
        ExerciseItemOutput,
    )
    from backend.src.models_schema.activity.review_item import (
        ReviewItem,
        ReviewItemOutput,
    )
    from backend.src.models_schema.interaction import Interaction

# ----- BASE ---- #


class StudyActivityBase(SQLModel):
    prompt: str | None
    activity_type: StudyActivityType
    activity_format: StudyActivityFormat
    subject_type: SubjectType


# ----- INPUT ----- #


class StudyActivityInput(StudyActivityBase):
    prompt: str


class FlashcardsActivityInput(SQLModel):
    subject_type: SubjectType
    name: str
    description: str


# ----- OUTPUT ----- #


class StudyActivityOutput(StudyActivityBase):
    id: int
    name: str
    description: str
    created_at: datetime

    is_submitted: bool
    submitted_at: datetime | None


class StudyActivityOutputComplete(StudyActivityOutput):
    items: list["ReviewItemOutput"] | list["ExerciseItemOutput"]


# ----- UPDATE ----- #


class StudyActivityUpdate(SQLModel):
    name: Annotated[str | None, BeforeValidator(beva_forbid_none)] = None
    description: Annotated[str | None, BeforeValidator(beva_forbid_none)] = None


# ----- TABLE MODEL ----- #


class StudyActivity(StudyActivityBase, table=True):
    __tablename__ = "study_activity"  # type: ignore

    id: Annotated[int | None, Field(primary_key=True, nullable=False)] = None
    interaction_id: Annotated[
        int | None,
        Field(foreign_key="interaction.id", nullable=False, ondelete="CASCADE"),
    ] = None

    # Name and description will be generated by LLM first, and then editable by user
    name: str
    description: str

    is_submitted: bool = False  # Exercise only

    created_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True)),
        default_factory=lambda: datetime.now(timezone.utc),
    )
    submitted_at: Annotated[
        datetime | None, Field(sa_column=Column(DateTime(timezone=True)))
    ] = None

    interaction: "Interaction" = Relationship(back_populates="study_activities")
    review_items: list["ReviewItem"] = Relationship(
        back_populates="study_activity", cascade_delete=True
    )
    exercise_items: list["ExerciseItem"] = Relationship(
        back_populates="study_activity", cascade_delete=True
    )

    __table_args__ = (
        CheckConstraint(
            """
            (activity_type = 'EXERCISE' AND activity_format IN ('MULTIPLE_CHOICE_QUESTIONS', 'OPEN_ENDED'))
            OR
            (activity_type = 'REVIEW' AND activity_format IN ('FLASHCARDS', 'GAP_FILL'))
            """,
            name="CK_activity_type_activity_format",
        ),
        CheckConstraint(
            """
            (activity_type = 'EXERCISE')
            OR
            (activity_type = 'REVIEW' AND is_submitted = false)
            """,
            name="CK_activity_type_is_submitted",
        ),
        CheckConstraint(
            """
            (activity_format = 'FLASHCARDS')
            OR
            (activity_format <> 'FLASHCARDS' AND prompt IS NOT NULL)
            """
        ),
    )

    @property
    def items(self) -> list[ExerciseItem] | list[ReviewItem]:
        if self.activity_type == StudyActivityType.EXERCISE:
            return self.exercise_items
        return self.review_items


from backend.src.models_schema.activity.exercise_item import (
    ExerciseItemOutput,
)
from backend.src.models_schema.activity.review_item import ReviewItemOutput
