from datetime import datetime, timezone
from typing import TYPE_CHECKING, Annotated, Optional

from pydantic import BaseModel
from sqlmodel import Column, DateTime, Field, Relationship, SQLModel

from backend.src.models_schema.enums import StudyActivityType, SubjectType

if TYPE_CHECKING:
    from backend.src.models_schema.activity.exercise_activity import ExerciseActivity
    from backend.src.models_schema.activity.review_activity import ReviewActivity
    from backend.src.models_schema.interaction import Interaction

# ----- BASE ---- #


class StudyActivityBase(SQLModel):
    prompt: str
    study_activity_type: StudyActivityType
    subject_type: SubjectType


# ----- INPUT ----- #


class StudyActivityInput(StudyActivityBase):
    pass


# ----- TABLE MODEL ----- #


class StudyActivity(StudyActivityBase, table=True):
    __tablename__ = "study_activity"  # type: ignore

    id: Annotated[int | None, Field(primary_key=True, nullable=False)] = None
    interaction_id: Annotated[
        int | None,
        Field(foreign_key="interaction.id", nullable=False, ondelete="CASCADE"),
    ] = None

    # Name and description will be generated by LLM first, and then editable by user
    name: str
    description: str

    created_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True)),
        default_factory=lambda: datetime.now(timezone.utc),
    )

    interaction: "Interaction" = Relationship(back_populates="study_activities")
    exercise_activity: Optional["ExerciseActivity"] = Relationship(
        back_populates="study_activity", cascade_delete=True
    )
    review_activity: Optional["ReviewActivity"] = Relationship(
        back_populates="study_activity", cascade_delete=True
    )
