name: Basic CI Checks

on:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build backend docker image
        run: docker build -t backend-prod -f ./backend/Dockerfile.prod ./backend

      - name: Build frontend docker image
        run: docker build -t frontend-prod -f ./frontend/Dockerfile.prod ./frontend
