name: Basic CI Checks

on:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build backend docker image
        run: docker build -t backend-prod -f ./backend/Dockerfile.prod ./backend

      - name: Build frontend docker image
        run: docker build -t frontend-prod -f ./frontend/Dockerfile.prod ./frontend

  backend-pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Pytest using compose file
        run: docker compose -f docker-compose.backend.test.yml up --build --abort-on-container-exit --exit-code-from pytest-runner
